/*
 * generated by Xtext
 */
package org.xtext.mda.project;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BrowserDSLRuntimeModule extends org.xtext.mda.project.AbstractBrowserDSLRuntimeModule {

}
