/**
 * generated by Xtext
 */
package org.xtext.mda.project.ui.contentassist;

import org.xtext.mda.project.ui.contentassist.AbstractBrowserDSLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class BrowserDSLProposalProvider extends AbstractBrowserDSLProposalProvider {
}
