/*
* generated by Xtext
*/
package org.xtext.mda.project.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class BrowserDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSubAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSubSubroutineParserRuleCall_0_0 = (RuleCall)cSubAssignment_0.eContents().get(0);
		private final Assignment cMainAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMainMainParserRuleCall_1_0 = (RuleCall)cMainAssignment_1.eContents().get(0);
		
		//Program:
		//	sub+=Subroutine* main=Main;
		public ParserRule getRule() { return rule; }

		//sub+=Subroutine* main=Main
		public Group getGroup() { return cGroup; }

		//sub+=Subroutine*
		public Assignment getSubAssignment_0() { return cSubAssignment_0; }

		//Subroutine
		public RuleCall getSubSubroutineParserRuleCall_0_0() { return cSubSubroutineParserRuleCall_0_0; }

		//main=Main
		public Assignment getMainAssignment_1() { return cMainAssignment_1; }

		//Main
		public RuleCall getMainMainParserRuleCall_1_0() { return cMainMainParserRuleCall_1_0; }
	}

	public class SubroutineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Subroutine");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSubKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cHeadAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cHeadHeadParserRuleCall_1_0 = (RuleCall)cHeadAssignment_1.eContents().get(0);
		private final Assignment cBodyAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cBodyBodyParserRuleCall_2_0 = (RuleCall)cBodyAssignment_2.eContents().get(0);
		
		//Subroutine:
		//	"sub " head=Head body+=Body;
		public ParserRule getRule() { return rule; }

		//"sub " head=Head body+=Body
		public Group getGroup() { return cGroup; }

		//"sub "
		public Keyword getSubKeyword_0() { return cSubKeyword_0; }

		//head=Head
		public Assignment getHeadAssignment_1() { return cHeadAssignment_1; }

		//Head
		public RuleCall getHeadHeadParserRuleCall_1_0() { return cHeadHeadParserRuleCall_1_0; }

		//body+=Body
		public Assignment getBodyAssignment_2() { return cBodyAssignment_2; }

		//Body
		public RuleCall getBodyBodyParserRuleCall_2_0() { return cBodyBodyParserRuleCall_2_0; }
	}

	public class HeadElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Head");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cNameAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cNameFunctionNameParserRuleCall_0_0_0 = (RuleCall)cNameAssignment_0_0.eContents().get(0);
		private final Keyword cLeftParenthesisRightParenthesisKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cNameAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cNameFunctionNameParserRuleCall_1_0_0 = (RuleCall)cNameAssignment_1_0.eContents().get(0);
		private final Keyword cVarKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cVarIdAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cVarIdVariableNameParserRuleCall_1_2_0 = (RuleCall)cVarIdAssignment_1_2.eContents().get(0);
		private final Group cGroup_1_3 = (Group)cGroup_1.eContents().get(3);
		private final Keyword cVarKeyword_1_3_0 = (Keyword)cGroup_1_3.eContents().get(0);
		private final Assignment cVarIdAssignment_1_3_1 = (Assignment)cGroup_1_3.eContents().get(1);
		private final RuleCall cVarIdVariableNameParserRuleCall_1_3_1_0 = (RuleCall)cVarIdAssignment_1_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_4 = (Keyword)cGroup_1.eContents().get(4);
		
		//Head:
		//	name=FunctionName "()" | name=FunctionName "(var " varId+=VariableName (", var " varId+=VariableName)* ")";
		public ParserRule getRule() { return rule; }

		//name=FunctionName "()" | name=FunctionName "(var " varId+=VariableName (", var " varId+=VariableName)* ")"
		public Alternatives getAlternatives() { return cAlternatives; }

		//name=FunctionName "()"
		public Group getGroup_0() { return cGroup_0; }

		//name=FunctionName
		public Assignment getNameAssignment_0_0() { return cNameAssignment_0_0; }

		//FunctionName
		public RuleCall getNameFunctionNameParserRuleCall_0_0_0() { return cNameFunctionNameParserRuleCall_0_0_0; }

		//"()"
		public Keyword getLeftParenthesisRightParenthesisKeyword_0_1() { return cLeftParenthesisRightParenthesisKeyword_0_1; }

		//name=FunctionName "(var " varId+=VariableName (", var " varId+=VariableName)* ")"
		public Group getGroup_1() { return cGroup_1; }

		//name=FunctionName
		public Assignment getNameAssignment_1_0() { return cNameAssignment_1_0; }

		//FunctionName
		public RuleCall getNameFunctionNameParserRuleCall_1_0_0() { return cNameFunctionNameParserRuleCall_1_0_0; }

		//"(var "
		public Keyword getVarKeyword_1_1() { return cVarKeyword_1_1; }

		//varId+=VariableName
		public Assignment getVarIdAssignment_1_2() { return cVarIdAssignment_1_2; }

		//VariableName
		public RuleCall getVarIdVariableNameParserRuleCall_1_2_0() { return cVarIdVariableNameParserRuleCall_1_2_0; }

		//(", var " varId+=VariableName)*
		public Group getGroup_1_3() { return cGroup_1_3; }

		//", var "
		public Keyword getVarKeyword_1_3_0() { return cVarKeyword_1_3_0; }

		//varId+=VariableName
		public Assignment getVarIdAssignment_1_3_1() { return cVarIdAssignment_1_3_1; }

		//VariableName
		public RuleCall getVarIdVariableNameParserRuleCall_1_3_1_0() { return cVarIdVariableNameParserRuleCall_1_3_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_1_4() { return cRightParenthesisKeyword_1_4; }
	}

	public class FunctionReferenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionReference");
		private final Assignment cFunctionNameAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cFunctionNameFunctionNameCrossReference_0 = (CrossReference)cFunctionNameAssignment.eContents().get(0);
		private final RuleCall cFunctionNameFunctionNameIDTerminalRuleCall_0_1 = (RuleCall)cFunctionNameFunctionNameCrossReference_0.eContents().get(1);
		
		//FunctionReference:
		//	functionName=[FunctionName];
		public ParserRule getRule() { return rule; }

		//functionName=[FunctionName]
		public Assignment getFunctionNameAssignment() { return cFunctionNameAssignment; }

		//[FunctionName]
		public CrossReference getFunctionNameFunctionNameCrossReference_0() { return cFunctionNameFunctionNameCrossReference_0; }

		//ID
		public RuleCall getFunctionNameFunctionNameIDTerminalRuleCall_0_1() { return cFunctionNameFunctionNameIDTerminalRuleCall_0_1; }
	}

	public class VariableReferenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "VariableReference");
		private final Assignment cVarIDAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cVarIDVariableNameCrossReference_0 = (CrossReference)cVarIDAssignment.eContents().get(0);
		private final RuleCall cVarIDVariableNameIDTerminalRuleCall_0_1 = (RuleCall)cVarIDVariableNameCrossReference_0.eContents().get(1);
		
		//VariableReference:
		//	varID=[VariableName];
		public ParserRule getRule() { return rule; }

		//varID=[VariableName]
		public Assignment getVarIDAssignment() { return cVarIDAssignment; }

		//[VariableName]
		public CrossReference getVarIDVariableNameCrossReference_0() { return cVarIDVariableNameCrossReference_0; }

		//ID
		public RuleCall getVarIDVariableNameIDTerminalRuleCall_0_1() { return cVarIDVariableNameIDTerminalRuleCall_0_1; }
	}

	public class FunctionCallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionCall");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final RuleCall cFunctionReferenceParserRuleCall_0_0 = (RuleCall)cGroup_0.eContents().get(0);
		private final Keyword cLeftParenthesisRightParenthesisKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final RuleCall cFunctionReferenceParserRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cVarAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cVarExpressionParserRuleCall_1_2_0 = (RuleCall)cVarAssignment_1_2.eContents().get(0);
		private final Group cGroup_1_3 = (Group)cGroup_1.eContents().get(3);
		private final Keyword cCommaKeyword_1_3_0 = (Keyword)cGroup_1_3.eContents().get(0);
		private final Assignment cVarAssignment_1_3_1 = (Assignment)cGroup_1_3.eContents().get(1);
		private final RuleCall cVarExpressionParserRuleCall_1_3_1_0 = (RuleCall)cVarAssignment_1_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_4 = (Keyword)cGroup_1.eContents().get(4);
		
		//FunctionCall:
		//	FunctionReference "()" | FunctionReference "(" var+=Expression ("," var+=Expression)* ")";
		public ParserRule getRule() { return rule; }

		//FunctionReference "()" | FunctionReference "(" var+=Expression ("," var+=Expression)* ")"
		public Alternatives getAlternatives() { return cAlternatives; }

		//FunctionReference "()"
		public Group getGroup_0() { return cGroup_0; }

		//FunctionReference
		public RuleCall getFunctionReferenceParserRuleCall_0_0() { return cFunctionReferenceParserRuleCall_0_0; }

		//"()"
		public Keyword getLeftParenthesisRightParenthesisKeyword_0_1() { return cLeftParenthesisRightParenthesisKeyword_0_1; }

		//FunctionReference "(" var+=Expression ("," var+=Expression)* ")"
		public Group getGroup_1() { return cGroup_1; }

		//FunctionReference
		public RuleCall getFunctionReferenceParserRuleCall_1_0() { return cFunctionReferenceParserRuleCall_1_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1_1() { return cLeftParenthesisKeyword_1_1; }

		//var+=Expression
		public Assignment getVarAssignment_1_2() { return cVarAssignment_1_2; }

		//Expression
		public RuleCall getVarExpressionParserRuleCall_1_2_0() { return cVarExpressionParserRuleCall_1_2_0; }

		//("," var+=Expression)*
		public Group getGroup_1_3() { return cGroup_1_3; }

		//","
		public Keyword getCommaKeyword_1_3_0() { return cCommaKeyword_1_3_0; }

		//var+=Expression
		public Assignment getVarAssignment_1_3_1() { return cVarAssignment_1_3_1; }

		//Expression
		public RuleCall getVarExpressionParserRuleCall_1_3_1_0() { return cVarExpressionParserRuleCall_1_3_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_1_4() { return cRightParenthesisKeyword_1_4; }
	}

	public class FunctionNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionName");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//FunctionName:
		//	name=STRING;
		public ParserRule getRule() { return rule; }

		//name=STRING
		public Assignment getNameAssignment() { return cNameAssignment; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_0() { return cNameSTRINGTerminalRuleCall_0; }
	}

	public class MainElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Main");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMainKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cBodyParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Main:
		//	"main " Body;
		public ParserRule getRule() { return rule; }

		//"main " Body
		public Group getGroup() { return cGroup; }

		//"main "
		public Keyword getMainKeyword_0() { return cMainKeyword_0; }

		//Body
		public RuleCall getBodyParserRuleCall_1() { return cBodyParserRuleCall_1; }
	}

	public class BodyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Body");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBrowserKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cOpenAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cOpenOpenBrowserEnumRuleCall_1_0 = (RuleCall)cOpenAssignment_1.eContents().get(0);
		private final Keyword cSemicolonSpaceKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cInstructionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cInstructionsInstructionParserRuleCall_3_0 = (RuleCall)cInstructionsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSpaceKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cInstructionsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cInstructionsInstructionParserRuleCall_4_1_0 = (RuleCall)cInstructionsAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Body:
		//	"{browser" open=OpenBrowser "; " instructions+=Instruction (" " instructions+=Instruction)* "}";
		public ParserRule getRule() { return rule; }

		//"{browser" open=OpenBrowser "; " instructions+=Instruction (" " instructions+=Instruction)* "}"
		public Group getGroup() { return cGroup; }

		//"{browser"
		public Keyword getBrowserKeyword_0() { return cBrowserKeyword_0; }

		//open=OpenBrowser
		public Assignment getOpenAssignment_1() { return cOpenAssignment_1; }

		//OpenBrowser
		public RuleCall getOpenOpenBrowserEnumRuleCall_1_0() { return cOpenOpenBrowserEnumRuleCall_1_0; }

		//"; "
		public Keyword getSemicolonSpaceKeyword_2() { return cSemicolonSpaceKeyword_2; }

		//instructions+=Instruction
		public Assignment getInstructionsAssignment_3() { return cInstructionsAssignment_3; }

		//Instruction
		public RuleCall getInstructionsInstructionParserRuleCall_3_0() { return cInstructionsInstructionParserRuleCall_3_0; }

		//(" " instructions+=Instruction)*
		public Group getGroup_4() { return cGroup_4; }

		//" "
		public Keyword getSpaceKeyword_4_0() { return cSpaceKeyword_4_0; }

		//instructions+=Instruction
		public Assignment getInstructionsAssignment_4_1() { return cInstructionsAssignment_4_1; }

		//Instruction
		public RuleCall getInstructionsInstructionParserRuleCall_4_1_0() { return cInstructionsInstructionParserRuleCall_4_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class InstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Instruction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cDecAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cDecDeclarationParserRuleCall_0_0 = (RuleCall)cDecAssignment_0.eContents().get(0);
		private final Assignment cCondAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cCondConditionParserRuleCall_1_0 = (RuleCall)cCondAssignment_1.eContents().get(0);
		private final Assignment cWhileAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cWhileWhileParserRuleCall_2_0 = (RuleCall)cWhileAssignment_2.eContents().get(0);
		private final Assignment cActAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final RuleCall cActActionInstructionParserRuleCall_3_0 = (RuleCall)cActAssignment_3.eContents().get(0);
		private final Assignment cAssAssignment_4 = (Assignment)cAlternatives.eContents().get(4);
		private final RuleCall cAssAssignationParserRuleCall_4_0 = (RuleCall)cAssAssignment_4.eContents().get(0);
		private final Assignment cSubAssignment_5 = (Assignment)cAlternatives.eContents().get(5);
		private final RuleCall cSubFunctionCallParserRuleCall_5_0 = (RuleCall)cSubAssignment_5.eContents().get(0);
		
		//Instruction:
		//	dec=Declaration | cond=Condition | while=While | act=ActionInstruction | ass=Assignation | sub=FunctionCall;
		public ParserRule getRule() { return rule; }

		//dec=Declaration | cond=Condition | while=While | act=ActionInstruction | ass=Assignation | sub=FunctionCall
		public Alternatives getAlternatives() { return cAlternatives; }

		//dec=Declaration
		public Assignment getDecAssignment_0() { return cDecAssignment_0; }

		//Declaration
		public RuleCall getDecDeclarationParserRuleCall_0_0() { return cDecDeclarationParserRuleCall_0_0; }

		//cond=Condition
		public Assignment getCondAssignment_1() { return cCondAssignment_1; }

		//Condition
		public RuleCall getCondConditionParserRuleCall_1_0() { return cCondConditionParserRuleCall_1_0; }

		//while=While
		public Assignment getWhileAssignment_2() { return cWhileAssignment_2; }

		//While
		public RuleCall getWhileWhileParserRuleCall_2_0() { return cWhileWhileParserRuleCall_2_0; }

		//act=ActionInstruction
		public Assignment getActAssignment_3() { return cActAssignment_3; }

		//ActionInstruction
		public RuleCall getActActionInstructionParserRuleCall_3_0() { return cActActionInstructionParserRuleCall_3_0; }

		//ass=Assignation
		public Assignment getAssAssignment_4() { return cAssAssignment_4; }

		//Assignation
		public RuleCall getAssAssignationParserRuleCall_4_0() { return cAssAssignationParserRuleCall_4_0; }

		//sub=FunctionCall
		public Assignment getSubAssignment_5() { return cSubAssignment_5; }

		//FunctionCall
		public RuleCall getSubFunctionCallParserRuleCall_5_0() { return cSubFunctionCallParserRuleCall_5_0; }
	}

	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Condition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIfKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cAllKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cAnyKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpExpressionParserRuleCall_3_0 = (RuleCall)cExpAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cThenKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cInsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cInsInstructionParserRuleCall_6_0 = (RuleCall)cInsAssignment_6.eContents().get(0);
		private final Keyword cElseKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cIns2Assignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cIns2InstructionParserRuleCall_8_0 = (RuleCall)cIns2Assignment_8.eContents().get(0);
		private final Keyword cEndifKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Condition:
		//	"if " ("all " | "any ")? "(" exp=Expression ")" "then " ins+=Instruction+ "else " ins2+=Instruction+ "endif";
		public ParserRule getRule() { return rule; }

		//"if " ("all " | "any ")? "(" exp=Expression ")" "then " ins+=Instruction+ "else " ins2+=Instruction+ "endif"
		public Group getGroup() { return cGroup; }

		//"if "
		public Keyword getIfKeyword_0() { return cIfKeyword_0; }

		//("all " | "any ")?
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//"all "
		public Keyword getAllKeyword_1_0() { return cAllKeyword_1_0; }

		//"any "
		public Keyword getAnyKeyword_1_1() { return cAnyKeyword_1_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }

		//exp=Expression
		public Assignment getExpAssignment_3() { return cExpAssignment_3; }

		//Expression
		public RuleCall getExpExpressionParserRuleCall_3_0() { return cExpExpressionParserRuleCall_3_0; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }

		//"then "
		public Keyword getThenKeyword_5() { return cThenKeyword_5; }

		//ins+=Instruction+
		public Assignment getInsAssignment_6() { return cInsAssignment_6; }

		//Instruction
		public RuleCall getInsInstructionParserRuleCall_6_0() { return cInsInstructionParserRuleCall_6_0; }

		//"else "
		public Keyword getElseKeyword_7() { return cElseKeyword_7; }

		//ins2+=Instruction+
		public Assignment getIns2Assignment_8() { return cIns2Assignment_8; }

		//Instruction
		public RuleCall getIns2InstructionParserRuleCall_8_0() { return cIns2InstructionParserRuleCall_8_0; }

		//"endif"
		public Keyword getEndifKeyword_9() { return cEndifKeyword_9; }
	}

	public class WhileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "While");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWhileKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cExpAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExpExpressionParserRuleCall_1_0 = (RuleCall)cExpAssignment_1.eContents().get(0);
		private final Keyword cDoKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cInsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cInsInstructionParserRuleCall_3_0 = (RuleCall)cInsAssignment_3.eContents().get(0);
		private final Keyword cEndwhileKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//While:
		//	"while (" exp=Expression ") do " ins+=Instruction+ " endwhile";
		public ParserRule getRule() { return rule; }

		//"while (" exp=Expression ") do " ins+=Instruction+ " endwhile"
		public Group getGroup() { return cGroup; }

		//"while ("
		public Keyword getWhileKeyword_0() { return cWhileKeyword_0; }

		//exp=Expression
		public Assignment getExpAssignment_1() { return cExpAssignment_1; }

		//Expression
		public RuleCall getExpExpressionParserRuleCall_1_0() { return cExpExpressionParserRuleCall_1_0; }

		//") do "
		public Keyword getDoKeyword_2() { return cDoKeyword_2; }

		//ins+=Instruction+
		public Assignment getInsAssignment_3() { return cInsAssignment_3; }

		//Instruction
		public RuleCall getInsInstructionParserRuleCall_3_0() { return cInsInstructionParserRuleCall_3_0; }

		//" endwhile"
		public Keyword getEndwhileKeyword_4() { return cEndwhileKeyword_4; }
	}

	public class ActionInstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ActionInstruction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cActionAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cActionClickParserRuleCall_0_0 = (RuleCall)cActionAssignment_0.eContents().get(0);
		private final Assignment cActionAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cActionCheckParserRuleCall_1_0 = (RuleCall)cActionAssignment_1.eContents().get(0);
		private final Assignment cActionAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cActionFillParserRuleCall_2_0 = (RuleCall)cActionAssignment_2.eContents().get(0);
		private final Assignment cActionAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final RuleCall cActionClearParserRuleCall_3_0 = (RuleCall)cActionAssignment_3.eContents().get(0);
		private final RuleCall cGoToParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//ActionInstruction:
		//	action=Click | action=Check | action=Fill | action=Clear | GoTo;
		public ParserRule getRule() { return rule; }

		//action=Click | action=Check | action=Fill | action=Clear | GoTo
		public Alternatives getAlternatives() { return cAlternatives; }

		//action=Click
		public Assignment getActionAssignment_0() { return cActionAssignment_0; }

		//Click
		public RuleCall getActionClickParserRuleCall_0_0() { return cActionClickParserRuleCall_0_0; }

		//action=Check
		public Assignment getActionAssignment_1() { return cActionAssignment_1; }

		//Check
		public RuleCall getActionCheckParserRuleCall_1_0() { return cActionCheckParserRuleCall_1_0; }

		//action=Fill
		public Assignment getActionAssignment_2() { return cActionAssignment_2; }

		//Fill
		public RuleCall getActionFillParserRuleCall_2_0() { return cActionFillParserRuleCall_2_0; }

		//action=Clear
		public Assignment getActionAssignment_3() { return cActionAssignment_3; }

		//Clear
		public RuleCall getActionClearParserRuleCall_3_0() { return cActionClearParserRuleCall_3_0; }

		//GoTo
		public RuleCall getGoToParserRuleCall_4() { return cGoToParserRuleCall_4; }
	}

	public class VariableNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "VariableName");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//VariableName:
		//	name=STRING;
		public ParserRule getRule() { return rule; }

		//name=STRING
		public Assignment getNameAssignment() { return cNameAssignment; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_0() { return cNameSTRINGTerminalRuleCall_0; }
	}

	public class DeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Declaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameVariableNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSpaceEqualsSignSpaceKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValExpressionParserRuleCall_3_0 = (RuleCall)cValAssignment_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Declaration:
		//	"var " name=VariableName " = " val=Expression ";";
		public ParserRule getRule() { return rule; }

		//"var " name=VariableName " = " val=Expression ";"
		public Group getGroup() { return cGroup; }

		//"var "
		public Keyword getVarKeyword_0() { return cVarKeyword_0; }

		//name=VariableName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//VariableName
		public RuleCall getNameVariableNameParserRuleCall_1_0() { return cNameVariableNameParserRuleCall_1_0; }

		//" = "
		public Keyword getSpaceEqualsSignSpaceKeyword_2() { return cSpaceEqualsSignSpaceKeyword_2; }

		//val=Expression
		public Assignment getValAssignment_3() { return cValAssignment_3; }

		//Expression
		public RuleCall getValExpressionParserRuleCall_3_0() { return cValExpressionParserRuleCall_3_0; }

		//";"
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}

	public class AssignationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Assignation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVarAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cVarVariableReferenceParserRuleCall_0_0 = (RuleCall)cVarAssignment_0.eContents().get(0);
		private final Keyword cSpaceEqualsSignSpaceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cExprAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cExprExpressionParserRuleCall_2_0 = (RuleCall)cExprAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Assignation:
		//	var=VariableReference " = " expr=Expression ";";
		public ParserRule getRule() { return rule; }

		//var=VariableReference " = " expr=Expression ";"
		public Group getGroup() { return cGroup; }

		//var=VariableReference
		public Assignment getVarAssignment_0() { return cVarAssignment_0; }

		//VariableReference
		public RuleCall getVarVariableReferenceParserRuleCall_0_0() { return cVarVariableReferenceParserRuleCall_0_0; }

		//" = "
		public Keyword getSpaceEqualsSignSpaceKeyword_1() { return cSpaceEqualsSignSpaceKeyword_1; }

		//expr=Expression
		public Assignment getExprAssignment_2() { return cExprAssignment_2; }

		//Expression
		public RuleCall getExprExpressionParserRuleCall_2_0() { return cExprExpressionParserRuleCall_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cTypeTypeParserRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Assignment cVarAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cVarVariableParserRuleCall_1_0 = (RuleCall)cVarAssignment_1.eContents().get(0);
		private final Assignment cActAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cActActionExpressionParserRuleCall_2_0 = (RuleCall)cActAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Alternatives cAlternatives_3_0 = (Alternatives)cGroup_3.eContents().get(0);
		private final Keyword cSpaceEqualsSignEqualsSignSpaceKeyword_3_0_0 = (Keyword)cAlternatives_3_0.eContents().get(0);
		private final Keyword cSpaceGreaterThanSignSpaceKeyword_3_0_1 = (Keyword)cAlternatives_3_0.eContents().get(1);
		private final Keyword cSpaceLessThanSignSpaceKeyword_3_0_2 = (Keyword)cAlternatives_3_0.eContents().get(2);
		private final Assignment cLeftAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cLeftExpressionParserRuleCall_3_1_0 = (RuleCall)cLeftAssignment_3_1.eContents().get(0);
		private final Assignment cRightAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cRightExpressionParserRuleCall_3_2_0 = (RuleCall)cRightAssignment_3_2.eContents().get(0);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Keyword cSpaceExclamationMarkKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cExpAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cExpExpressionParserRuleCall_4_1_0 = (RuleCall)cExpAssignment_4_1.eContents().get(0);
		
		//Expression:
		//	type=Type | var=Variable | act=ActionExpression | (" == " | " > " | " < ") left=Expression right=Expression | " !"
		//	exp=Expression;
		public ParserRule getRule() { return rule; }

		//type=Type | var=Variable | act=ActionExpression | (" == " | " > " | " < ") left=Expression right=Expression | " !"
		//exp=Expression
		public Alternatives getAlternatives() { return cAlternatives; }

		//type=Type
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }

		//Type
		public RuleCall getTypeTypeParserRuleCall_0_0() { return cTypeTypeParserRuleCall_0_0; }

		//var=Variable
		public Assignment getVarAssignment_1() { return cVarAssignment_1; }

		//Variable
		public RuleCall getVarVariableParserRuleCall_1_0() { return cVarVariableParserRuleCall_1_0; }

		//act=ActionExpression
		public Assignment getActAssignment_2() { return cActAssignment_2; }

		//ActionExpression
		public RuleCall getActActionExpressionParserRuleCall_2_0() { return cActActionExpressionParserRuleCall_2_0; }

		//(" == " | " > " | " < ") left=Expression right=Expression
		public Group getGroup_3() { return cGroup_3; }

		//" == " | " > " | " < "
		public Alternatives getAlternatives_3_0() { return cAlternatives_3_0; }

		//" == "
		public Keyword getSpaceEqualsSignEqualsSignSpaceKeyword_3_0_0() { return cSpaceEqualsSignEqualsSignSpaceKeyword_3_0_0; }

		//" > "
		public Keyword getSpaceGreaterThanSignSpaceKeyword_3_0_1() { return cSpaceGreaterThanSignSpaceKeyword_3_0_1; }

		//" < "
		public Keyword getSpaceLessThanSignSpaceKeyword_3_0_2() { return cSpaceLessThanSignSpaceKeyword_3_0_2; }

		//left=Expression
		public Assignment getLeftAssignment_3_1() { return cLeftAssignment_3_1; }

		//Expression
		public RuleCall getLeftExpressionParserRuleCall_3_1_0() { return cLeftExpressionParserRuleCall_3_1_0; }

		//right=Expression
		public Assignment getRightAssignment_3_2() { return cRightAssignment_3_2; }

		//Expression
		public RuleCall getRightExpressionParserRuleCall_3_2_0() { return cRightExpressionParserRuleCall_3_2_0; }

		//" !" exp=Expression
		public Group getGroup_4() { return cGroup_4; }

		//" !"
		public Keyword getSpaceExclamationMarkKeyword_4_0() { return cSpaceExclamationMarkKeyword_4_0; }

		//exp=Expression
		public Assignment getExpAssignment_4_1() { return cExpAssignment_4_1; }

		//Expression
		public RuleCall getExpExpressionParserRuleCall_4_1_0() { return cExpExpressionParserRuleCall_4_1_0; }
	}

	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cBoolKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cStringKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cIntKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		
		//Type:
		//	"bool " | "string " | "int ";
		public ParserRule getRule() { return rule; }

		//"bool " | "string " | "int "
		public Alternatives getAlternatives() { return cAlternatives; }

		//"bool "
		public Keyword getBoolKeyword_0() { return cBoolKeyword_0; }

		//"string "
		public Keyword getStringKeyword_1() { return cStringKeyword_1; }

		//"int "
		public Keyword getIntKeyword_2() { return cIntKeyword_2; }
	}

	public class VariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Variable");
		private final Assignment cVarAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cVarVariableReferenceParserRuleCall_0 = (RuleCall)cVarAssignment.eContents().get(0);
		
		//Variable:
		//	var=VariableReference;
		public ParserRule getRule() { return rule; }

		//var=VariableReference
		public Assignment getVarAssignment() { return cVarAssignment; }

		//VariableReference
		public RuleCall getVarVariableReferenceParserRuleCall_0() { return cVarVariableReferenceParserRuleCall_0; }
	}

	public class ActionExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ActionExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cExprAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cExprVerifyParserRuleCall_0_0 = (RuleCall)cExprAssignment_0.eContents().get(0);
		private final Assignment cExprAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cExprExistParserRuleCall_1_0 = (RuleCall)cExprAssignment_1.eContents().get(0);
		
		//ActionExpression:
		//	expr=Verify | expr=Exist;
		public ParserRule getRule() { return rule; }

		//expr=Verify | expr=Exist
		public Alternatives getAlternatives() { return cAlternatives; }

		//expr=Verify
		public Assignment getExprAssignment_0() { return cExprAssignment_0; }

		//Verify
		public RuleCall getExprVerifyParserRuleCall_0_0() { return cExprVerifyParserRuleCall_0_0; }

		//expr=Exist
		public Assignment getExprAssignment_1() { return cExprAssignment_1; }

		//Exist
		public RuleCall getExprExistParserRuleCall_1_0() { return cExprExistParserRuleCall_1_0; }
	}

	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Element");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cClickableElementParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFillableElementParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCheckableElementParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Element:
		//	ClickableElement | FillableElement | CheckableElement;
		public ParserRule getRule() { return rule; }

		//ClickableElement | FillableElement | CheckableElement
		public Alternatives getAlternatives() { return cAlternatives; }

		//ClickableElement
		public RuleCall getClickableElementParserRuleCall_0() { return cClickableElementParserRuleCall_0; }

		//FillableElement
		public RuleCall getFillableElementParserRuleCall_1() { return cFillableElementParserRuleCall_1; }

		//CheckableElement
		public RuleCall getCheckableElementParserRuleCall_2() { return cCheckableElementParserRuleCall_2; }
	}

	public class ClickableElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ClickableElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLinkParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cButtonParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cImageParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//ClickableElement:
		//	Link | Button | Image;
		public ParserRule getRule() { return rule; }

		//Link | Button | Image
		public Alternatives getAlternatives() { return cAlternatives; }

		//Link
		public RuleCall getLinkParserRuleCall_0() { return cLinkParserRuleCall_0; }

		//Button
		public RuleCall getButtonParserRuleCall_1() { return cButtonParserRuleCall_1; }

		//Image
		public RuleCall getImageParserRuleCall_2() { return cImageParserRuleCall_2; }
	}

	public class FillableElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FillableElement");
		private final RuleCall cTextFieldParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//FillableElement:
		//	TextField;
		public ParserRule getRule() { return rule; }

		//TextField
		public RuleCall getTextFieldParserRuleCall() { return cTextFieldParserRuleCall; }
	}

	public class CheckableElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CheckableElement");
		private final RuleCall cCheckboxParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//CheckableElement:
		//	Checkbox;
		public ParserRule getRule() { return rule; }

		//Checkbox
		public RuleCall getCheckboxParserRuleCall() { return cCheckboxParserRuleCall; }
	}

	public class CheckboxElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Checkbox");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCheckboxKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cCheckAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cCheckSTRINGTerminalRuleCall_1_0_0 = (RuleCall)cCheckAssignment_1_0.eContents().get(0);
		private final RuleCall cVariableParserRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		
		//Checkbox:
		//	"checkbox " (check=STRING | Variable);
		public ParserRule getRule() { return rule; }

		//"checkbox " (check=STRING | Variable)
		public Group getGroup() { return cGroup; }

		//"checkbox "
		public Keyword getCheckboxKeyword_0() { return cCheckboxKeyword_0; }

		//check=STRING | Variable
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//check=STRING
		public Assignment getCheckAssignment_1_0() { return cCheckAssignment_1_0; }

		//STRING
		public RuleCall getCheckSTRINGTerminalRuleCall_1_0_0() { return cCheckSTRINGTerminalRuleCall_1_0_0; }

		//Variable
		public RuleCall getVariableParserRuleCall_1_1() { return cVariableParserRuleCall_1_1; }
	}

	public class LinkElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Link");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLinkKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cLinkAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cLinkSTRINGTerminalRuleCall_1_0_0 = (RuleCall)cLinkAssignment_1_0.eContents().get(0);
		private final RuleCall cVariableParserRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		
		//Link:
		//	"link " (link=STRING | Variable);
		public ParserRule getRule() { return rule; }

		//"link " (link=STRING | Variable)
		public Group getGroup() { return cGroup; }

		//"link "
		public Keyword getLinkKeyword_0() { return cLinkKeyword_0; }

		//link=STRING | Variable
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//link=STRING
		public Assignment getLinkAssignment_1_0() { return cLinkAssignment_1_0; }

		//STRING
		public RuleCall getLinkSTRINGTerminalRuleCall_1_0_0() { return cLinkSTRINGTerminalRuleCall_1_0_0; }

		//Variable
		public RuleCall getVariableParserRuleCall_1_1() { return cVariableParserRuleCall_1_1; }
	}

	public class ButtonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Button");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cButtonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cButAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cButSTRINGTerminalRuleCall_1_0_0 = (RuleCall)cButAssignment_1_0.eContents().get(0);
		private final RuleCall cVariableParserRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		
		//Button:
		//	"button " (but=STRING | Variable);
		public ParserRule getRule() { return rule; }

		//"button " (but=STRING | Variable)
		public Group getGroup() { return cGroup; }

		//"button "
		public Keyword getButtonKeyword_0() { return cButtonKeyword_0; }

		//but=STRING | Variable
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//but=STRING
		public Assignment getButAssignment_1_0() { return cButAssignment_1_0; }

		//STRING
		public RuleCall getButSTRINGTerminalRuleCall_1_0_0() { return cButSTRINGTerminalRuleCall_1_0_0; }

		//Variable
		public RuleCall getVariableParserRuleCall_1_1() { return cVariableParserRuleCall_1_1; }
	}

	public class ImageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Image");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cImgAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cImgSTRINGTerminalRuleCall_1_0_0 = (RuleCall)cImgAssignment_1_0.eContents().get(0);
		private final RuleCall cVariableParserRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		
		//Image:
		//	"image " (img=STRING | Variable);
		public ParserRule getRule() { return rule; }

		//"image " (img=STRING | Variable)
		public Group getGroup() { return cGroup; }

		//"image "
		public Keyword getImageKeyword_0() { return cImageKeyword_0; }

		//img=STRING | Variable
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//img=STRING
		public Assignment getImgAssignment_1_0() { return cImgAssignment_1_0; }

		//STRING
		public RuleCall getImgSTRINGTerminalRuleCall_1_0_0() { return cImgSTRINGTerminalRuleCall_1_0_0; }

		//Variable
		public RuleCall getVariableParserRuleCall_1_1() { return cVariableParserRuleCall_1_1; }
	}

	public class TextFieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TextField");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTextFieldKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cTextAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cTextSTRINGTerminalRuleCall_1_0_0 = (RuleCall)cTextAssignment_1_0.eContents().get(0);
		private final RuleCall cVariableParserRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		
		//TextField:
		//	"textField " (text=STRING | Variable);
		public ParserRule getRule() { return rule; }

		//"textField " (text=STRING | Variable)
		public Group getGroup() { return cGroup; }

		//"textField "
		public Keyword getTextFieldKeyword_0() { return cTextFieldKeyword_0; }

		//text=STRING | Variable
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//text=STRING
		public Assignment getTextAssignment_1_0() { return cTextAssignment_1_0; }

		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_1_0_0() { return cTextSTRINGTerminalRuleCall_1_0_0; }

		//Variable
		public RuleCall getVariableParserRuleCall_1_1() { return cVariableParserRuleCall_1_1; }
	}

	public class TypeElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TypeElement");
		private final Assignment cElemAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cElemAlternatives_0 = (Alternatives)cElemAssignment.eContents().get(0);
		private final Keyword cElemCheckboxKeyword_0_0 = (Keyword)cElemAlternatives_0.eContents().get(0);
		private final Keyword cElemLinkKeyword_0_1 = (Keyword)cElemAlternatives_0.eContents().get(1);
		private final Keyword cElemButtonKeyword_0_2 = (Keyword)cElemAlternatives_0.eContents().get(2);
		private final Keyword cElemImageKeyword_0_3 = (Keyword)cElemAlternatives_0.eContents().get(3);
		private final Keyword cElemTextFieldKeyword_0_4 = (Keyword)cElemAlternatives_0.eContents().get(4);
		
		//TypeElement:
		//	elem=("checkbox" | "link" | "button" | "image" | "textField");
		public ParserRule getRule() { return rule; }

		//elem=("checkbox" | "link" | "button" | "image" | "textField")
		public Assignment getElemAssignment() { return cElemAssignment; }

		//"checkbox" | "link" | "button" | "image" | "textField"
		public Alternatives getElemAlternatives_0() { return cElemAlternatives_0; }

		//"checkbox"
		public Keyword getElemCheckboxKeyword_0_0() { return cElemCheckboxKeyword_0_0; }

		//"link"
		public Keyword getElemLinkKeyword_0_1() { return cElemLinkKeyword_0_1; }

		//"button"
		public Keyword getElemButtonKeyword_0_2() { return cElemButtonKeyword_0_2; }

		//"image"
		public Keyword getElemImageKeyword_0_3() { return cElemImageKeyword_0_3; }

		//"textField"
		public Keyword getElemTextFieldKeyword_0_4() { return cElemTextFieldKeyword_0_4; }
	}

	public class SelectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Select");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSelectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueTypeElementParserRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Select:
		//	"select(" value=TypeElement ")";
		public ParserRule getRule() { return rule; }

		//"select(" value=TypeElement ")"
		public Group getGroup() { return cGroup; }

		//"select("
		public Keyword getSelectKeyword_0() { return cSelectKeyword_0; }

		//value=TypeElement
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//TypeElement
		public RuleCall getValueTypeElementParserRuleCall_1_0() { return cValueTypeElementParserRuleCall_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}

	public class ClickElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Click");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClickKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cValAlternatives_1_0 = (Alternatives)cValAssignment_1.eContents().get(0);
		private final RuleCall cValClickableElementParserRuleCall_1_0_0 = (RuleCall)cValAlternatives_1_0.eContents().get(0);
		private final RuleCall cValSelectParserRuleCall_1_0_1 = (RuleCall)cValAlternatives_1_0.eContents().get(1);
		private final Keyword cRightParenthesisSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Click:
		//	"click(" val=(ClickableElement | Select) ");";
		public ParserRule getRule() { return rule; }

		//"click(" val=(ClickableElement | Select) ");"
		public Group getGroup() { return cGroup; }

		//"click("
		public Keyword getClickKeyword_0() { return cClickKeyword_0; }

		//val=(ClickableElement | Select)
		public Assignment getValAssignment_1() { return cValAssignment_1; }

		//ClickableElement | Select
		public Alternatives getValAlternatives_1_0() { return cValAlternatives_1_0; }

		//ClickableElement
		public RuleCall getValClickableElementParserRuleCall_1_0_0() { return cValClickableElementParserRuleCall_1_0_0; }

		//Select
		public RuleCall getValSelectParserRuleCall_1_0_1() { return cValSelectParserRuleCall_1_0_1; }

		//");"
		public Keyword getRightParenthesisSemicolonKeyword_2() { return cRightParenthesisSemicolonKeyword_2; }
	}

	public class CheckElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Check");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCheckKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cValAlternatives_1_0 = (Alternatives)cValAssignment_1.eContents().get(0);
		private final RuleCall cValCheckableElementParserRuleCall_1_0_0 = (RuleCall)cValAlternatives_1_0.eContents().get(0);
		private final RuleCall cValSelectParserRuleCall_1_0_1 = (RuleCall)cValAlternatives_1_0.eContents().get(1);
		private final Keyword cRightParenthesisSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Check:
		//	"check(" val=(CheckableElement | Select) ");";
		public ParserRule getRule() { return rule; }

		//"check(" val=(CheckableElement | Select) ");"
		public Group getGroup() { return cGroup; }

		//"check("
		public Keyword getCheckKeyword_0() { return cCheckKeyword_0; }

		//val=(CheckableElement | Select)
		public Assignment getValAssignment_1() { return cValAssignment_1; }

		//CheckableElement | Select
		public Alternatives getValAlternatives_1_0() { return cValAlternatives_1_0; }

		//CheckableElement
		public RuleCall getValCheckableElementParserRuleCall_1_0_0() { return cValCheckableElementParserRuleCall_1_0_0; }

		//Select
		public RuleCall getValSelectParserRuleCall_1_0_1() { return cValSelectParserRuleCall_1_0_1; }

		//");"
		public Keyword getRightParenthesisSemicolonKeyword_2() { return cRightParenthesisSemicolonKeyword_2; }
	}

	public class FillElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Fill");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFillKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cValAlternatives_1_0 = (Alternatives)cValAssignment_1.eContents().get(0);
		private final RuleCall cValFillableElementParserRuleCall_1_0_0 = (RuleCall)cValAlternatives_1_0.eContents().get(0);
		private final RuleCall cValSelectParserRuleCall_1_0_1 = (RuleCall)cValAlternatives_1_0.eContents().get(1);
		private final Keyword cValueKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cSTRINGTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Keyword cRightParenthesisSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Fill:
		//	"fill(" val=(FillableElement | Select) ", value=" STRING ");";
		public ParserRule getRule() { return rule; }

		//"fill(" val=(FillableElement | Select) ", value=" STRING ");"
		public Group getGroup() { return cGroup; }

		//"fill("
		public Keyword getFillKeyword_0() { return cFillKeyword_0; }

		//val=(FillableElement | Select)
		public Assignment getValAssignment_1() { return cValAssignment_1; }

		//FillableElement | Select
		public Alternatives getValAlternatives_1_0() { return cValAlternatives_1_0; }

		//FillableElement
		public RuleCall getValFillableElementParserRuleCall_1_0_0() { return cValFillableElementParserRuleCall_1_0_0; }

		//Select
		public RuleCall getValSelectParserRuleCall_1_0_1() { return cValSelectParserRuleCall_1_0_1; }

		//", value="
		public Keyword getValueKeyword_2() { return cValueKeyword_2; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_3() { return cSTRINGTerminalRuleCall_3; }

		//");"
		public Keyword getRightParenthesisSemicolonKeyword_4() { return cRightParenthesisSemicolonKeyword_4; }
	}

	public class ClearElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Clear");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClearKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final RuleCall cFillableElementParserRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final RuleCall cCheckableElementParserRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		private final RuleCall cSelectParserRuleCall_1_2 = (RuleCall)cAlternatives_1.eContents().get(2);
		private final Keyword cRightParenthesisSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Clear:
		//	"clear(" (FillableElement | CheckableElement | Select) ");";
		public ParserRule getRule() { return rule; }

		//"clear(" (FillableElement | CheckableElement | Select) ");"
		public Group getGroup() { return cGroup; }

		//"clear("
		public Keyword getClearKeyword_0() { return cClearKeyword_0; }

		//FillableElement | CheckableElement | Select
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//FillableElement
		public RuleCall getFillableElementParserRuleCall_1_0() { return cFillableElementParserRuleCall_1_0; }

		//CheckableElement
		public RuleCall getCheckableElementParserRuleCall_1_1() { return cCheckableElementParserRuleCall_1_1; }

		//Select
		public RuleCall getSelectParserRuleCall_1_2() { return cSelectParserRuleCall_1_2; }

		//");"
		public Keyword getRightParenthesisSemicolonKeyword_2() { return cRightParenthesisSemicolonKeyword_2; }
	}

	public class VerifyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Verify");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVerifyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final RuleCall cFillableElementParserRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final RuleCall cCheckableElementParserRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		private final RuleCall cSelectParserRuleCall_1_2 = (RuleCall)cAlternatives_1.eContents().get(2);
		private final Keyword cValueKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cSTRINGTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Keyword cRightParenthesisSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Verify:
		//	"verify(" (FillableElement | CheckableElement | Select) ", value=" STRING ");";
		public ParserRule getRule() { return rule; }

		//"verify(" (FillableElement | CheckableElement | Select) ", value=" STRING ");"
		public Group getGroup() { return cGroup; }

		//"verify("
		public Keyword getVerifyKeyword_0() { return cVerifyKeyword_0; }

		//FillableElement | CheckableElement | Select
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//FillableElement
		public RuleCall getFillableElementParserRuleCall_1_0() { return cFillableElementParserRuleCall_1_0; }

		//CheckableElement
		public RuleCall getCheckableElementParserRuleCall_1_1() { return cCheckableElementParserRuleCall_1_1; }

		//Select
		public RuleCall getSelectParserRuleCall_1_2() { return cSelectParserRuleCall_1_2; }

		//", value="
		public Keyword getValueKeyword_2() { return cValueKeyword_2; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_3() { return cSTRINGTerminalRuleCall_3; }

		//");"
		public Keyword getRightParenthesisSemicolonKeyword_4() { return cRightParenthesisSemicolonKeyword_4; }
	}

	public class ExistElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Exist");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExistKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cValAlternatives_1_0 = (Alternatives)cValAssignment_1.eContents().get(0);
		private final RuleCall cValElementParserRuleCall_1_0_0 = (RuleCall)cValAlternatives_1_0.eContents().get(0);
		private final RuleCall cValSelectParserRuleCall_1_0_1 = (RuleCall)cValAlternatives_1_0.eContents().get(1);
		private final Keyword cRightParenthesisSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Exist:
		//	"exist(" val=(Element | Select) ");";
		public ParserRule getRule() { return rule; }

		//"exist(" val=(Element | Select) ");"
		public Group getGroup() { return cGroup; }

		//"exist("
		public Keyword getExistKeyword_0() { return cExistKeyword_0; }

		//val=(Element | Select)
		public Assignment getValAssignment_1() { return cValAssignment_1; }

		//Element | Select
		public Alternatives getValAlternatives_1_0() { return cValAlternatives_1_0; }

		//Element
		public RuleCall getValElementParserRuleCall_1_0_0() { return cValElementParserRuleCall_1_0_0; }

		//Select
		public RuleCall getValSelectParserRuleCall_1_0_1() { return cValSelectParserRuleCall_1_0_1; }

		//");"
		public Keyword getRightParenthesisSemicolonKeyword_2() { return cRightParenthesisSemicolonKeyword_2; }
	}

	public class GoToElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "GoTo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGoToKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cUrlAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cUrlURLTerminalRuleCall_1_0 = (RuleCall)cUrlAssignment_1.eContents().get(0);
		private final Keyword cRightParenthesisSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//GoTo:
		//	"goTo(" url=URL ");";
		public ParserRule getRule() { return rule; }

		//"goTo(" url=URL ");"
		public Group getGroup() { return cGroup; }

		//"goTo("
		public Keyword getGoToKeyword_0() { return cGoToKeyword_0; }

		//url=URL
		public Assignment getUrlAssignment_1() { return cUrlAssignment_1; }

		//URL
		public RuleCall getUrlURLTerminalRuleCall_1_0() { return cUrlURLTerminalRuleCall_1_0; }

		//");"
		public Keyword getRightParenthesisSemicolonKeyword_2() { return cRightParenthesisSemicolonKeyword_2; }
	}
	
	
	public class OpenBrowserElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "OpenBrowser");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cChromeEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cChromeChromeKeyword_0_0 = (Keyword)cChromeEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFirefoxEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFirefoxFirefoxKeyword_1_0 = (Keyword)cFirefoxEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum OpenBrowser:
		//	Chrome | Firefox;
		public EnumRule getRule() { return rule; }

		//Chrome | Firefox
		public Alternatives getAlternatives() { return cAlternatives; }

		//Chrome
		public EnumLiteralDeclaration getChromeEnumLiteralDeclaration_0() { return cChromeEnumLiteralDeclaration_0; }

		//"Chrome"
		public Keyword getChromeChromeKeyword_0_0() { return cChromeChromeKeyword_0_0; }

		//Firefox
		public EnumLiteralDeclaration getFirefoxEnumLiteralDeclaration_1() { return cFirefoxEnumLiteralDeclaration_1; }

		//"Firefox"
		public Keyword getFirefoxFirefoxKeyword_1_0() { return cFirefoxFirefoxKeyword_1_0; }
	}
	
	private final ProgramElements pProgram;
	private final SubroutineElements pSubroutine;
	private final HeadElements pHead;
	private final FunctionReferenceElements pFunctionReference;
	private final VariableReferenceElements pVariableReference;
	private final FunctionCallElements pFunctionCall;
	private final FunctionNameElements pFunctionName;
	private final MainElements pMain;
	private final BodyElements pBody;
	private final OpenBrowserElements unknownRuleOpenBrowser;
	private final InstructionElements pInstruction;
	private final ConditionElements pCondition;
	private final WhileElements pWhile;
	private final ActionInstructionElements pActionInstruction;
	private final VariableNameElements pVariableName;
	private final DeclarationElements pDeclaration;
	private final AssignationElements pAssignation;
	private final ExpressionElements pExpression;
	private final TypeElements pType;
	private final VariableElements pVariable;
	private final ActionExpressionElements pActionExpression;
	private final ElementElements pElement;
	private final ClickableElementElements pClickableElement;
	private final FillableElementElements pFillableElement;
	private final CheckableElementElements pCheckableElement;
	private final CheckboxElements pCheckbox;
	private final LinkElements pLink;
	private final ButtonElements pButton;
	private final ImageElements pImage;
	private final TextFieldElements pTextField;
	private final TypeElementElements pTypeElement;
	private final SelectElements pSelect;
	private final ClickElements pClick;
	private final CheckElements pCheck;
	private final FillElements pFill;
	private final ClearElements pClear;
	private final VerifyElements pVerify;
	private final ExistElements pExist;
	private final GoToElements pGoTo;
	private final TerminalRule tURL;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BrowserDSLGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgram = new ProgramElements();
		this.pSubroutine = new SubroutineElements();
		this.pHead = new HeadElements();
		this.pFunctionReference = new FunctionReferenceElements();
		this.pVariableReference = new VariableReferenceElements();
		this.pFunctionCall = new FunctionCallElements();
		this.pFunctionName = new FunctionNameElements();
		this.pMain = new MainElements();
		this.pBody = new BodyElements();
		this.unknownRuleOpenBrowser = new OpenBrowserElements();
		this.pInstruction = new InstructionElements();
		this.pCondition = new ConditionElements();
		this.pWhile = new WhileElements();
		this.pActionInstruction = new ActionInstructionElements();
		this.pVariableName = new VariableNameElements();
		this.pDeclaration = new DeclarationElements();
		this.pAssignation = new AssignationElements();
		this.pExpression = new ExpressionElements();
		this.pType = new TypeElements();
		this.pVariable = new VariableElements();
		this.pActionExpression = new ActionExpressionElements();
		this.pElement = new ElementElements();
		this.pClickableElement = new ClickableElementElements();
		this.pFillableElement = new FillableElementElements();
		this.pCheckableElement = new CheckableElementElements();
		this.pCheckbox = new CheckboxElements();
		this.pLink = new LinkElements();
		this.pButton = new ButtonElements();
		this.pImage = new ImageElements();
		this.pTextField = new TextFieldElements();
		this.pTypeElement = new TypeElementElements();
		this.pSelect = new SelectElements();
		this.pClick = new ClickElements();
		this.pCheck = new CheckElements();
		this.pFill = new FillElements();
		this.pClear = new ClearElements();
		this.pVerify = new VerifyElements();
		this.pExist = new ExistElements();
		this.pGoTo = new GoToElements();
		this.tURL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "URL");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.mda.project.BrowserDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Program:
	//	sub+=Subroutine* main=Main;
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}

	//Subroutine:
	//	"sub " head=Head body+=Body;
	public SubroutineElements getSubroutineAccess() {
		return pSubroutine;
	}
	
	public ParserRule getSubroutineRule() {
		return getSubroutineAccess().getRule();
	}

	//Head:
	//	name=FunctionName "()" | name=FunctionName "(var " varId+=VariableName (", var " varId+=VariableName)* ")";
	public HeadElements getHeadAccess() {
		return pHead;
	}
	
	public ParserRule getHeadRule() {
		return getHeadAccess().getRule();
	}

	//FunctionReference:
	//	functionName=[FunctionName];
	public FunctionReferenceElements getFunctionReferenceAccess() {
		return pFunctionReference;
	}
	
	public ParserRule getFunctionReferenceRule() {
		return getFunctionReferenceAccess().getRule();
	}

	//VariableReference:
	//	varID=[VariableName];
	public VariableReferenceElements getVariableReferenceAccess() {
		return pVariableReference;
	}
	
	public ParserRule getVariableReferenceRule() {
		return getVariableReferenceAccess().getRule();
	}

	//FunctionCall:
	//	FunctionReference "()" | FunctionReference "(" var+=Expression ("," var+=Expression)* ")";
	public FunctionCallElements getFunctionCallAccess() {
		return pFunctionCall;
	}
	
	public ParserRule getFunctionCallRule() {
		return getFunctionCallAccess().getRule();
	}

	//FunctionName:
	//	name=STRING;
	public FunctionNameElements getFunctionNameAccess() {
		return pFunctionName;
	}
	
	public ParserRule getFunctionNameRule() {
		return getFunctionNameAccess().getRule();
	}

	//Main:
	//	"main " Body;
	public MainElements getMainAccess() {
		return pMain;
	}
	
	public ParserRule getMainRule() {
		return getMainAccess().getRule();
	}

	//Body:
	//	"{browser" open=OpenBrowser "; " instructions+=Instruction (" " instructions+=Instruction)* "}";
	public BodyElements getBodyAccess() {
		return pBody;
	}
	
	public ParserRule getBodyRule() {
		return getBodyAccess().getRule();
	}

	//enum OpenBrowser:
	//	Chrome | Firefox;
	public OpenBrowserElements getOpenBrowserAccess() {
		return unknownRuleOpenBrowser;
	}
	
	public EnumRule getOpenBrowserRule() {
		return getOpenBrowserAccess().getRule();
	}

	//Instruction:
	//	dec=Declaration | cond=Condition | while=While | act=ActionInstruction | ass=Assignation | sub=FunctionCall;
	public InstructionElements getInstructionAccess() {
		return pInstruction;
	}
	
	public ParserRule getInstructionRule() {
		return getInstructionAccess().getRule();
	}

	//Condition:
	//	"if " ("all " | "any ")? "(" exp=Expression ")" "then " ins+=Instruction+ "else " ins2+=Instruction+ "endif";
	public ConditionElements getConditionAccess() {
		return pCondition;
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}

	//While:
	//	"while (" exp=Expression ") do " ins+=Instruction+ " endwhile";
	public WhileElements getWhileAccess() {
		return pWhile;
	}
	
	public ParserRule getWhileRule() {
		return getWhileAccess().getRule();
	}

	//ActionInstruction:
	//	action=Click | action=Check | action=Fill | action=Clear | GoTo;
	public ActionInstructionElements getActionInstructionAccess() {
		return pActionInstruction;
	}
	
	public ParserRule getActionInstructionRule() {
		return getActionInstructionAccess().getRule();
	}

	//VariableName:
	//	name=STRING;
	public VariableNameElements getVariableNameAccess() {
		return pVariableName;
	}
	
	public ParserRule getVariableNameRule() {
		return getVariableNameAccess().getRule();
	}

	//Declaration:
	//	"var " name=VariableName " = " val=Expression ";";
	public DeclarationElements getDeclarationAccess() {
		return pDeclaration;
	}
	
	public ParserRule getDeclarationRule() {
		return getDeclarationAccess().getRule();
	}

	//Assignation:
	//	var=VariableReference " = " expr=Expression ";";
	public AssignationElements getAssignationAccess() {
		return pAssignation;
	}
	
	public ParserRule getAssignationRule() {
		return getAssignationAccess().getRule();
	}

	//Expression:
	//	type=Type | var=Variable | act=ActionExpression | (" == " | " > " | " < ") left=Expression right=Expression | " !"
	//	exp=Expression;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}

	//Type:
	//	"bool " | "string " | "int ";
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}

	//Variable:
	//	var=VariableReference;
	public VariableElements getVariableAccess() {
		return pVariable;
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}

	//ActionExpression:
	//	expr=Verify | expr=Exist;
	public ActionExpressionElements getActionExpressionAccess() {
		return pActionExpression;
	}
	
	public ParserRule getActionExpressionRule() {
		return getActionExpressionAccess().getRule();
	}

	//Element:
	//	ClickableElement | FillableElement | CheckableElement;
	public ElementElements getElementAccess() {
		return pElement;
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}

	//ClickableElement:
	//	Link | Button | Image;
	public ClickableElementElements getClickableElementAccess() {
		return pClickableElement;
	}
	
	public ParserRule getClickableElementRule() {
		return getClickableElementAccess().getRule();
	}

	//FillableElement:
	//	TextField;
	public FillableElementElements getFillableElementAccess() {
		return pFillableElement;
	}
	
	public ParserRule getFillableElementRule() {
		return getFillableElementAccess().getRule();
	}

	//CheckableElement:
	//	Checkbox;
	public CheckableElementElements getCheckableElementAccess() {
		return pCheckableElement;
	}
	
	public ParserRule getCheckableElementRule() {
		return getCheckableElementAccess().getRule();
	}

	//Checkbox:
	//	"checkbox " (check=STRING | Variable);
	public CheckboxElements getCheckboxAccess() {
		return pCheckbox;
	}
	
	public ParserRule getCheckboxRule() {
		return getCheckboxAccess().getRule();
	}

	//Link:
	//	"link " (link=STRING | Variable);
	public LinkElements getLinkAccess() {
		return pLink;
	}
	
	public ParserRule getLinkRule() {
		return getLinkAccess().getRule();
	}

	//Button:
	//	"button " (but=STRING | Variable);
	public ButtonElements getButtonAccess() {
		return pButton;
	}
	
	public ParserRule getButtonRule() {
		return getButtonAccess().getRule();
	}

	//Image:
	//	"image " (img=STRING | Variable);
	public ImageElements getImageAccess() {
		return pImage;
	}
	
	public ParserRule getImageRule() {
		return getImageAccess().getRule();
	}

	//TextField:
	//	"textField " (text=STRING | Variable);
	public TextFieldElements getTextFieldAccess() {
		return pTextField;
	}
	
	public ParserRule getTextFieldRule() {
		return getTextFieldAccess().getRule();
	}

	//TypeElement:
	//	elem=("checkbox" | "link" | "button" | "image" | "textField");
	public TypeElementElements getTypeElementAccess() {
		return pTypeElement;
	}
	
	public ParserRule getTypeElementRule() {
		return getTypeElementAccess().getRule();
	}

	//Select:
	//	"select(" value=TypeElement ")";
	public SelectElements getSelectAccess() {
		return pSelect;
	}
	
	public ParserRule getSelectRule() {
		return getSelectAccess().getRule();
	}

	//Click:
	//	"click(" val=(ClickableElement | Select) ");";
	public ClickElements getClickAccess() {
		return pClick;
	}
	
	public ParserRule getClickRule() {
		return getClickAccess().getRule();
	}

	//Check:
	//	"check(" val=(CheckableElement | Select) ");";
	public CheckElements getCheckAccess() {
		return pCheck;
	}
	
	public ParserRule getCheckRule() {
		return getCheckAccess().getRule();
	}

	//Fill:
	//	"fill(" val=(FillableElement | Select) ", value=" STRING ");";
	public FillElements getFillAccess() {
		return pFill;
	}
	
	public ParserRule getFillRule() {
		return getFillAccess().getRule();
	}

	//Clear:
	//	"clear(" (FillableElement | CheckableElement | Select) ");";
	public ClearElements getClearAccess() {
		return pClear;
	}
	
	public ParserRule getClearRule() {
		return getClearAccess().getRule();
	}

	//Verify:
	//	"verify(" (FillableElement | CheckableElement | Select) ", value=" STRING ");";
	public VerifyElements getVerifyAccess() {
		return pVerify;
	}
	
	public ParserRule getVerifyRule() {
		return getVerifyAccess().getRule();
	}

	//Exist:
	//	"exist(" val=(Element | Select) ");";
	public ExistElements getExistAccess() {
		return pExist;
	}
	
	public ParserRule getExistRule() {
		return getExistAccess().getRule();
	}

	//GoTo:
	//	"goTo(" url=URL ");";
	public GoToElements getGoToAccess() {
		return pGoTo;
	}
	
	public ParserRule getGoToRule() {
		return getGoToAccess().getRule();
	}

	//// Query terminal URL:
	//	"a".."z"+ // Protocol
	//	"://" ("0".."9"+ "." "0".."9"+ "." "0".."9"+ "." "0".."9"+ // Hostname
	//	| ("a".."z" | "A".."Z") ("a".."z" | "A".."Z" | "0".."9" | "$" | "-" | "_" | "\\" ("0".."9" | "a".."f" | "A".."F")
	//	("0".."9" | "a".."f" | "A".."F") | "%" "0".."9" "0".."9")* ("." ("a".."z" | "A".."Z") ("a".."z" | "A".."Z" | "0".."9"
	//	| "$" | "-" | "_" | "\\" ("0".."9" | "a".."f" | "A".."F") ("0".."9" | "a".."f" | "A".."F") | "%" "0".."9"
	//	"0".."9")*)*) (":" "0".."9"+)? // Portnumber
	//	("/" ("a".."z" | "A".."Z" | "0".."9" | "$" | "-" | "_" | "~" | "+" | "." | "\\" ("0".."9" | "a".."f" | "A".."F")
	//	("0".."9" | "a".."f" | "A".."F") | "%" "0".."9" "0".."9")*)* // Path
	//	("?" ("a".."z" | "A".."Z" | "0".."9" | "$" | "-" | "_" | "=" | "&" | ";" | "\\" ("0".."9" | "a".."f" | "A".."F")
	//	("0".."9" | "a".."f" | "A".."F") | "%" "0".."9" "0".."9")+ ("+" ("a".."z" | "A".."Z" | "0".."9" | "$" | "-" | "_" |
	//	"=" | "&" | ";" | "\\" ("0".."9" | "a".."f" | "A".."F") ("0".."9" | "a".."f" | "A".."F") | "%" "0".."9"
	//	"0".."9")+)*)?;
	public TerminalRule getURLRule() {
		return tURL;
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
