/**
 * generated by Xtext
 */
package org.xtext.mda.project.validation;

import org.xtext.mda.project.validation.AbstractBrowserDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class BrowserDSLValidator extends AbstractBrowserDSLValidator {
}
