/*
 * generated by Xtext
 */
package org.xtext.mda.project.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BrowserDSLUiModule extends org.xtext.mda.project.ui.AbstractBrowserDSLUiModule {
	public BrowserDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
